2024-11-08 09:24:40,042 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 09:37:30,822 - application_logger - DEBUG - Calling get_token in views.py with args: (<class 'base.views.MyTokenObtainPairSerializer'>, <User: coral>), kwargs: {} | User ID: 123 | Object ID: 456
2024-11-08 09:37:30,833 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-08 09:37:30,888 - application_logger - DEBUG - Calling list_by_user in views.py with args: (<base.views.GroupListViewSet object at 0x10389c680>, <rest_framework.request.Request: GET '/grouplists/by-user/1/'>), kwargs: {'user_id': '1'} | User ID: 123 | Object ID: 456
2024-11-08 09:37:30,896 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-08 09:37:51,668 - application_logger - DEBUG - Calling list_by_user in views.py with args: (<base.views.GroupListViewSet object at 0x1037ffda0>, <rest_framework.request.Request: GET '/grouplists/by-user/1/'>), kwargs: {'user_id': '1'} | User ID: 123 | Object ID: 456
2024-11-08 09:37:51,679 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-08 10:54:23,363 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:23,984 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:35,390 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:35,780 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:37,968 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:38,194 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:40,326 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:40,554 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:47,877 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:48,093 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:52,299 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:52,499 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:56,717 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:56,959 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:59,112 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:59,330 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:01,489 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:01,689 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:03,837 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:04,151 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:07,362 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:07,585 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:11,788 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:12,088 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:16,307 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:16,614 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:20,989 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:21,252 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:28,565 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:28,833 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:31,043 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:31,261 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:39,592 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:39,840 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:56:47,962 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-08 10:56:48,441 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:57:01,921 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-08 10:57:02,287 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:57:04,472 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-08 10:57:04,757 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:15,553 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:15,941 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:21,214 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:21,432 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:22,589 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:22,853 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:25,022 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:25,254 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:27,398 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:27,627 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:40,060 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:40,423 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:43,652 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:43,883 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:58,390 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:58:58,863 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:03,007 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:03,224 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:14,624 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:14,975 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:18,195 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:18,447 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:23,713 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:23,949 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 11:01:11,735 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 11:01:12,112 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:20:22,252 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:20:22,811 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:32:26,448 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:01,090 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:01,500 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:02,649 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:02,882 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:06,038 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:06,214 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:07,355 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:07,608 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:35:28,894 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:35:29,214 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:35:33,377 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:35:33,599 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:17,863 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:18,254 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:20,405 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:20,658 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:25,959 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:26,203 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:31,464 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:31,706 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:39:09,601 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:33:00,538 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:33:00,602 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:33:47,039 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:33:52,711 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:34:52,005 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:45:19,878 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:45:19,928 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:46:49,054 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:46:49,118 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:48:15,809 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:48:15,865 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:50:57,620 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:50:57,667 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:17,037 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:17,095 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:26,814 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:26,916 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1030a3e00>.
2024-11-10 09:55:11,441 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:55:12,029 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:55:50,230 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:55:50,574 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:55:59,949 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:00,289 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:06,456 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:06,792 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:12,031 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:12,401 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:14,583 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:14,828 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:17,998 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:18,251 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:19,380 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:19,622 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:20,784 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:21,092 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:24,556 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:56:24,612 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1069e6330>.
2024-11-10 09:58:26,614 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:26,651 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:36,155 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:36,201 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x106a587a0>.
2024-11-10 09:58:46,812 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:46,989 - django.request - WARNING - Not Found: /favicon.ico
2024-11-10 09:59:42,614 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:59:42,664 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:59:53,027 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:59:53,075 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x106c86180>.
2024-11-10 10:00:04,771 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:01:00,288 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:01:00,699 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:01:06,529 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:03:53,066 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:04:45,872 - django.request - WARNING - Unauthorized: /listitem/1/
2024-11-10 10:06:00,865 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:06:00,871 - django.request - WARNING - Bad Request: /listitem/1/
2024-11-10 10:06:16,918 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:06:16,924 - django.request - WARNING - Bad Request: /listitem/1/
2024-11-10 10:07:20,126 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:07:20,186 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 41, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x107f91f40>.
2024-11-10 10:07:48,966 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:07:49,004 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 41, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x109096360>.
2024-11-10 10:20:21,996 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:22,036 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:34,540 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:34,567 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:34,615 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:47,215 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:47,281 - django.request - ERROR - Internal Server Error: /listitem/4/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 41, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1090e7e90>.
2024-11-10 10:22:21,890 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:22:22,639 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:22:24,290 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:22:24,295 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108f5f530>. | User ID: 123 | Object ID: 456
2024-11-10 10:22:24,329 - django.request - ERROR - Internal Server Error: /listitem/4/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108f5f530>.
2024-11-10 10:22:53,292 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:22:53,390 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:22:57,407 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:23:00,785 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:23:04,218 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:23:04,227 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff5280>. | User ID: 123 | Object ID: 456
2024-11-10 10:23:04,286 - django.request - ERROR - Internal Server Error: /listitem/4/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff5280>.
2024-11-10 10:23:32,093 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:10,833 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:10,873 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:15,987 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:15,993 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108e98d70>. | User ID: 123 | Object ID: 456
2024-11-10 10:24:16,034 - django.request - ERROR - Internal Server Error: /listitem/3/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108e98d70>.
2024-11-10 10:27:15,382 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:27:15,443 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:27:19,347 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:27:19,353 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff7b90>. | User ID: 123 | Object ID: 456
2024-11-10 10:27:19,402 - django.request - ERROR - Internal Server Error: /listitem/3/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff7b90>.
2024-11-10 10:35:19,790 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:19,854 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:27,219 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:40,607 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:40,612 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108fbb4d0>. | User ID: 123 | Object ID: 456
2024-11-10 10:35:40,689 - django.request - ERROR - Internal Server Error: /listitem/3/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108fbb4d0>.
2024-11-10 10:39:53,131 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:39:53,648 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:39:54,808 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:39:55,052 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:04,869 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:05,240 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:21,972 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:22,411 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:26,634 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:26,910 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:34,188 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:34,454 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:45:11,530 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:45:11,992 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:45:47,027 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:45:47,553 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:46:51,762 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:47:12,915 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:13,006 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:22,424 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:22,445 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:22,482 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:41,905 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:41,915 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:47:41,917 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 10:48:07,456 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:48:07,462 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:48:07,462 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 10:49:57,885 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:02,676 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:02,692 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:02,732 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:07,168 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:07,174 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:50:07,176 - django.request - WARNING - Forbidden: /listitem/6/
2024-11-10 10:52:51,228 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:52:51,702 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:52:53,876 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:52:54,106 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:53:09,548 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:53:10,004 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:54:30,179 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:54:30,625 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:54:33,888 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:54:34,243 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:55:04,770 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:55:27,005 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:55:27,083 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:55:46,762 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:55:46,828 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:55:46,829 - django.request - WARNING - Forbidden: /listitem/6/
2024-11-10 11:02:54,875 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 11:02:55,341 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 11:04:37,374 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:37,579 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:47,233 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:47,237 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:04:47,238 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 11:04:47,268 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:59,783 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:59,788 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:04:59,789 - django.request - WARNING - Forbidden: /listitem/4/
2024-11-10 11:04:59,824 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:05:41,905 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:05:41,912 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:05:41,917 - django.request - WARNING - Forbidden: /listitem/6/
2024-11-10 11:05:41,953 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:08:33,002 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:08:33,018 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:08:33,019 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 11:13:57,641 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:13:57,723 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:02,179 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:02,183 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:02,229 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:07,165 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:07,170 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:07,211 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:23,425 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:23,437 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:14:23,438 - django.request - WARNING - Forbidden: /listitem/5/
2024-11-10 11:14:54,776 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:54,833 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:59,039 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:59,043 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:59,072 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:09,720 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:09,725 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:09,757 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:25,405 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:25,410 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:25,474 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:46,359 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:10,126 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:10,218 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:28,552 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:28,619 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:34,224 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:34,228 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:34,263 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:38,663 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:38,667 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:38,691 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:24:30,678 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:24:30,684 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:24:30,807 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:05:22,066 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:05:22,164 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:11,315 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:11,402 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:16,918 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:16,923 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:16,956 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:56,640 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:10:15,997 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:10:16,078 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:10:19,333 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:11:39,196 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:11:39,261 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:01,831 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:01,889 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:08,662 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:32,088 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:32,096 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:32,170 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:17:39,150 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:17:39,229 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:02,506 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:02,552 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:02,655 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:31,402 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:31,414 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:31,481 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:48,382 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:48,386 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:48,429 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:10,501 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:10,589 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:17,338 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:17,344 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:17,387 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:38,938 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:39,011 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:39,096 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:53,119 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:53,126 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:53,177 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:04,245 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:04,251 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:04,300 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:22,300 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:22,305 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:22,343 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:41:40,541 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 12:41:56,587 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:41:56,624 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:51:36,496 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:51:36,598 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:02:29,063 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:02:29,624 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:02:34,898 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:02:35,120 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:02:36,280 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:02:36,570 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:02:55,096 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:02:55,454 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:03:06,843 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:03:07,160 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:03:26,656 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:03:26,975 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:03:35,229 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:03:35,458 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:03:56,975 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:03:57,295 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:03,045 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:03,393 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:04,569 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:04,787 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:10,027 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:10,263 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:11,431 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:11,672 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:12,838 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:13,075 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:14,201 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:14,410 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:17,519 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:17,856 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:21,074 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:21,394 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:31,732 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:05:32,069 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:51,658 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/serializer.py changed, reloading.
2024-11-10 13:05:52,033 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:05:59,352 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/serializer.py changed, reloading.
2024-11-10 13:05:59,709 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:06:30,584 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/serializer.py changed, reloading.
2024-11-10 13:06:30,931 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:07:14,156 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:07:14,504 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:07:24,822 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:07:25,136 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:07:33,424 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:07:33,736 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:07:36,830 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:07:37,069 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:07:40,187 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:07:40,390 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:05,127 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:08:05,506 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:15,848 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:08:16,188 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:32,758 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:08:33,095 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:35,281 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:08:35,531 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:43,842 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:08:44,108 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:45,262 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:08:45,486 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:08:48,678 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:08:48,920 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:09:16,762 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:09:17,194 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:09:27,596 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:09:27,961 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:10:23,342 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:10:23,775 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:10:24,917 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:10:25,156 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:10:26,308 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:10:26,534 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:10:30,735 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:10:30,956 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:10:34,161 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:10:34,402 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:14:45,173 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:14:45,227 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:15:14,194 - django.request - WARNING - Not Found: /get_user_info/neni@walla.com
2024-11-10 13:15:54,165 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:15:54,210 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:16:05,774 - django.request - WARNING - Not Found: /get_user_info/neni@walla.com
2024-11-10 13:16:55,656 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:16:55,700 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:17:04,406 - django.request - WARNING - Not Found: /get_user_info/neni@walla.com/
2024-11-10 13:18:08,647 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:18:09,066 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:18:12,262 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/urls.py changed, reloading.
2024-11-10 13:18:12,494 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:19:00,765 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:19:01,126 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:19:04,325 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:19:04,589 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:19:19,886 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:19:19,914 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:25:12,077 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:25:12,142 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:25:24,599 - django.request - ERROR - Internal Server Error: /get_user_info/"neni@walla.com"/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 233, in get_user_info_by_email
    user = User.objects.get(email=email)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2024-11-10 13:26:29,590 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:26:29,615 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:26:42,108 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:28:31,298 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:28:31,708 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:28:35,942 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:28:36,213 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:28:37,389 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:28:37,754 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:28:42,562 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:28:42,598 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:29:01,534 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 13:29:01,540 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:29:27,950 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:29:27,979 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:30:10,715 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:30:10,819 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:30:57,325 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:30:57,362 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:31:04,394 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:31:04,414 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:31:04,519 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:32:17,866 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:32:17,907 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:32:29,880 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 13:32:29,901 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:33:23,528 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:33:23,591 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:33:30,462 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 13:33:30,480 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:35:55,719 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:35:56,103 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:35:59,299 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:35:59,514 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:36:02,712 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:36:02,957 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:36:30,449 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:36:30,477 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:36:43,177 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 13:36:43,195 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:37:12,542 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:37:23,990 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:37:24,044 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:38:18,165 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:38:18,217 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:40:29,050 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:40:29,094 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:40:47,352 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:40:47,407 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:41:35,156 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:41:35,171 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:41:35,238 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:41:45,301 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:41:45,316 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:41:45,340 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:42:35,406 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:42:35,499 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:43:20,518 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:43:20,623 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:44:05,277 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:05,689 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:06,868 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:07,114 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:09,259 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:09,547 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:10,678 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:10,913 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:16,137 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:16,402 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:18,550 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:18,787 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:19,928 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:20,153 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:24,342 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:24,582 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:27,778 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:28,018 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:31,133 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:31,360 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:34,464 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:34,707 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:35,762 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:44:35,976 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:44:47,613 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:44:47,676 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:48:31,205 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:31,551 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:33,639 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:33,856 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:35,938 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:36,205 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:40,328 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:40,540 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:42,628 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:42,846 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:50,182 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:50,425 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:51,596 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:51,815 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:53,983 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:54,202 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:55,285 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:55,500 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:48:57,669 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:48:57,899 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:00,052 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:00,270 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:01,325 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:01,570 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:03,776 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:04,019 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:14,387 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:14,642 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:17,845 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:18,080 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:21,260 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:21,511 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:25,728 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:25,963 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:30,188 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:30,424 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:35,638 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:35,888 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:37,984 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:38,214 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:42,438 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:49:42,705 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:49:54,611 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:50:02,689 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:50:02,735 - application_logger - ERROR - Error in list_by_user: can only concatenate str (not "int") to str | User ID: 123 | Object ID: 456
2024-11-10 13:50:02,813 - django.request - ERROR - Internal Server Error: /grouplists/by-user/2/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 149, in list_by_user
    print('userrrrrr           ' + user_id)
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: can only concatenate str (not "int") to str
2024-11-10 13:50:12,220 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:50:12,621 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:50:15,802 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:50:16,048 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:50:17,197 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:50:17,487 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:50:19,644 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:50:19,869 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:50:30,226 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:50:30,322 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:52:02,746 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:52:03,182 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:52:14,607 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:52:15,005 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:52:50,457 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:52:50,457 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 13:52:50,512 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:53:03,595 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:53:03,613 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:53:03,642 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:54:21,585 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:54:21,699 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:56:24,902 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:56:25,262 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:56:27,352 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:56:27,567 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:56:32,835 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:56:33,061 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:56:36,266 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:56:36,550 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:57:16,703 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 13:57:17,083 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 13:57:26,656 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:57:26,799 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:57:35,023 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 13:57:35,069 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:00:57,052 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:00:57,422 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:01:00,615 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:01:00,829 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:01:02,975 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:01:03,200 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:01:13,038 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:01:13,154 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:01:26,006 - django.request - WARNING - Unauthorized: /login
2024-11-10 14:01:29,795 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:01:29,856 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:01:51,113 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:01:51,178 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:02:13,514 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 14:02:13,541 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:02:23,127 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:02:23,202 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:03:36,260 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:03:36,667 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:03:39,867 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:03:40,130 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:03:42,302 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:03:42,528 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:03:45,706 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:03:45,943 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:04:01,407 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:04:01,748 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:04:20,320 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:04:20,373 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:04:34,031 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:04:34,085 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:04:45,705 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:04:45,717 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:04:45,735 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:17,073 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:17,085 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:17,126 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:22,507 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:22,514 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:22,540 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:36,942 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 14:05:36,959 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:07:07,100 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:07:13,476 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 14:07:13,485 - application_logger - ERROR - Error in create: {'list_item': [ErrorDetail(string='This field is required.', code='required')]} | User ID: 123 | Object ID: 456
2024-11-10 14:07:13,486 - django.request - WARNING - Bad Request: /grouplists/
2024-11-10 14:11:19,936 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:11:20,101 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:11:42,436 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:11:48,452 - application_logger - ERROR - Error in view: User matching query does not exist. | User ID: 123 | Object ID: 456
2024-11-10 14:11:48,481 - django.request - ERROR - Internal Server Error: /get_user_info/sdfsfsf/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 234, in get_user_info_by_email
    user = User.objects.get(email=email)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2024-11-10 14:14:14,804 - application_logger - ERROR - Error in view: User matching query does not exist. | User ID: 123 | Object ID: 456
2024-11-10 14:14:14,829 - django.request - ERROR - Internal Server Error: /get_user_info/sdfsfsf/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 234, in get_user_info_by_email
    user = User.objects.get(email=email)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2024-11-10 14:15:10,519 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:15:10,902 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:15:15,099 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 14:15:15,339 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 14:15:32,821 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:15:32,860 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:15:44,565 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 14:15:44,569 - django.request - WARNING - Not Found: /get_user_info/edd/
2024-11-10 14:18:18,981 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:18:19,021 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 14:18:24,866 - application_logger - INFO - Function view executed successfully in csrf.py | User ID: 123 | Object ID: 456
2024-11-10 14:18:24,866 - django.request - WARNING - Not Found: /get_user_info/feef/
